### ISSUE TITLE
Service workers in non-HTTPS, non-localhost network scenarios

### ISSUE THREAD

**Issue by ivanistheone** [openzim/warc2zim#56] opened 2020-08-20 14:40 UTC
If you try accessing kiwix-dev using http:// instead of https://  e.g. http://kiwix-dev.webrecorder.net/bouquineux/A/www.bouquineux.com/  you'll get the message

> This page must be loaded via an HTTPS URL to support service workers.
> Try Loading HTTPS URL?

According to 
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Setting_up_to_play_with_service_workers
service workers require HTTPS transport (or localhost).

This could be a problem for local area network deployments where `kiwix-serve` runs on one device (e.g. RPI) and clients connect access via LAN or WLAN using the browser.

**Comment by rgaudin** [comment] 2020-08-20 15:02
Duplicate of #24.

**Closed by rgaudin** 2020-08-20 15:02 UTC
