### ISSUE TITLE
Add a blocked domains list

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#63] opened 2020-10-20 16:59 UTC
Following-up on https://github.com/openzim/zimit/issues/31, it would be handy to have a list of domains that we unconditionally exclude because it's useless.

We can start, as suggested, with `*.doubleclick.net/` and `google-analytics.com/`.

Can be a list in the code or an external file that we load.

**Comment by kelson42** [comment] 2020-10-27 09:58
I think this is a good idea, but we should (at least) rely on a project maintaining such a list. See for example https://github.com/anudeepND/blacklist

**Comment by kelson42** [comment] 2020-11-05 08:37
Any reason to not consider this ticket as a duplicate of https://github.com/openzim/warc2zim/issues/63?

**Closed** 2021-01-12 06:31 UTC
Labels: enhancement
