### ISSUE TITLE
Custom CSS URL is not rewritten

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#263] opened 2024-05-21 03:27 UTC
Search boxes are still visible, but hsould not. Probably a stupid error in the css
https://farm.openzim.org/recipes/thalesdoc_en_all

**Comment by rgaudin** [comment] 2024-05-21 08:32
> Probably a stupid error in the css

If it was, it would be a zimfarm issue not a warc2zim one :)

But it's not! The CSS URL is not rewritten and thus blocked by CSP.

```html
<link type="text/css" href="https://warc2zim.kiwix.app/custom.css" rel="Stylesheet" />
```

**Comment by benoit74** [comment] 2024-05-21 08:35
Looks like we broke something indeed 🤣

**Comment by kelson42** [comment] 2024-05-21 10:12
I guess I have to relaunch my 5 days long scrape. But thx for the quick fix.

**Comment by benoit74** [comment] 2024-05-21 11:16
Fixed by https://github.com/openzim/warc2zim/pull/264

> I guess I have to relaunch my 5 days long scrape. But thx for the quick fix.

Not necessarily, we have the WARC file available, at least this would help to confirm the CSS works as intended

**Closed by benoit74** 2024-05-21 11:16 UTC
Labels: bug
