### ISSUE TITLE
Not all links seems rewrittem properly on "womenhistory"

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#379] opened 2024-08-18 14:24 UTC
See https://dev.library.kiwix.org/viewer#womenshistory.si.edu_en_all_2024-08/womenshistory.si.edu/learn/elementary
![image](https://github.com/user-attachments/assets/6ff99229-ed88-4ae8-9fc7-4360c173402b)

If I click on the article "Coloreando Nuestro Mundo" I will lea e the ZIM and do to https://womenshistory.si.edu/sites/default/files/documents/Coloreando%20Nuestro%20Mundo.pdf

... but I expect this page to be mirrored and so to have an internal link.

It seems the page is somehow mirrored but buggy, see:
<img width="1080" alt="image" src="https://github.com/user-attachments/assets/36a640da-1af1-4b81-a57b-5b3201a143b8">

**Comment by rgaudin** [comment] 2024-08-19 09:50
I can't reproduce. And no seach engine can find trace of a `Coloreando Nuestro Mundo.pdf` .

Your screenshot depicts another (known) issue: media queries images. As you can seen on my screencast, my resolution is the one that's in the ZIM, not yours.

https://github.com/user-attachments/assets/caed6a6c-9620-4e12-9063-41c27e895e81

**Comment by rgaudin** [comment] 2024-08-19 15:17
OK on that second issue, I have the answer: on the online website, those two PDF links lead to a `404` response. In warc2zim, we dont store 404 response and we consider links to stuff not-in-the-zim to be external.

So the behavior is the one we've agreed upon. I am closing this ticket for this reason.

**Closed by rgaudin** 2024-08-19 15:17 UTC
Labels: bug, question
